export const users = {
    SEARCH_USER: 'SEARCH_USER',
    LIST_USERS: 'FIND_USERS',
    FIND_USER_DETAIL: 'FIND_USER_DETAIL',
    NOT_FOUND_USER: 'NOT_FOUND_USER',
    REPOSITORIES_USER: 'REPOSITORIES_USER',
    REPOSITORIES_FAVORITE: 'REPOSITORIES_FAVORITE',
    IS_FAVORITE: 'IS_FAVORITE',
    REMOVE_FAVORITE: 'REMOVE_FAVORITE',
    SEARCH_REPOSITORIES: 'SEARCH_REPOSITORIES',
}